### ISSUE TITLE
Unable to beautify some specific EJS

### ISSUE THREAD

**Issue by seoker** [prettydiff/prettydiff#319]
Hi, I am using **atom-beautify** to beautify my source code, and I choose **prettydiff** to beautify EJS templates.
However, today I encounter an error that I cannot beautify my template, here is the template (unbeautified):
```ejs
<li>
  <span><%= provider.providerName %></span>
  <span>
      <span class='gs-currency'><%= provider.currency  %></span>
      <span class='gs-number gs-thousand-seperator'><%= provider.averagePrice  %></span> + fees
    </span>
  </li>
```

There's an error popped up from my atom, and here it comes the stack trace:
```
TypeError: Cannot read property 'indexOf' of undefined
    at markuppretty__tokenize_tag_cheat (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/lib/markuppretty.js:1292:108)
    at markuppretty__tokenize_tag (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/lib/markuppretty.js:1377:18)
    at markuppretty__tokenize (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/lib/markuppretty.js:1848:17)
    at markuppretty_ (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/lib/markuppretty.js:1860:6)
    at commonjs (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/lib/markuppretty.js:3481:16)
    at core_ (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2344:41)
    at prettydiff_ (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2484:12)
    at Object.commonjs [as api] (/Users/seokerwang/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2520:16)
    at /Users/seokerwang/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:123:27
    at Promise._execute (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:77:14)
    at PrettyDiff.module.exports.PrettyDiff.beautify (/Users/seokerwang/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:70:16)
    at /Users/seokerwang/.atom/packages/atom-beautify/src/beautifiers/index.coffee:284:24
    at Promise._execute (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:77:14)
    at /Users/seokerwang/.atom/packages/atom-beautify/src/beautifiers/index.coffee:207:18
    at tryCatcher (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:423:57)
    at ReductionPromiseArray._resolve (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/reduce.js:51:19)
    at Promise.completed [as _fulfillmentHandler0] (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/reduce.js:112:15)
    at Promise._settlePromise (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/seokerwang/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:17:14)
```

Please kindly remind me if I am missing anything, thanks.

**Comment by prettydiff** [comment]
I cannot reproduce the problem in the current version of Pretty Diff.  Atom Beautify is currently using an older version of Pretty Diff until I can find a different module solution to NPM.

The line in trouble appears to be this line: https://github.com/prettydiff/prettydiff/blob/63250d8f27087a932033a5d15ca10b65ff9862f3/lib/markuppretty.js#L1292

I will add an extra qualifier to the condition to ensure the problem never arises.

**Comment by seoker** [comment]
As I followed this thread https://github.com/Glavin001/atom-beautify/issues/881 and this thread https://github.com/prettydiff/prettydiff/issues/291
I understand what happened. Hope a good solution will come out.
