### ISSUE TITLE
diffspaceignore:true errors

### ISSUE THREAD

**Issue by cazgp** [prettydiff/prettydiff#332]
prettydiff Version: 2.1.0 Dated: 10 July 2016 ; Ubuntu 15.04.

```
$ prettydiff source:source.xml diff:diff.xml diffcli:true content:true diffspaceignore:true > output.html
/usr/lib/node_modules/prettydiff/lib/diffview.js:933
                    if (options.diffspaceignore === true && change === "replace" && baseTextArray[baseStart].replace(/\s+/g, "") === newTextArray[newStart].replace(/\s+/g, "")) {
                                                                                                                                                           ^

TypeError: Cannot read property 'replace' of undefined
    at diffview__report (/usr/lib/node_modules/prettydiff/lib/diffview.js:933:156)
    at diffview_ (/usr/lib/node_modules/prettydiff/lib/diffview.js:1302:6)
    at commonjs (/usr/lib/node_modules/prettydiff/lib/diffview.js:1308:16)
    at core__diff (/usr/lib/node_modules/prettydiff/prettydiff.js:890:46)
    at core_ (/usr/lib/node_modules/prettydiff/prettydiff.js:910:18)
    at prettydiff_ (/usr/lib/node_modules/prettydiff/prettydiff.js:943:12)
    at Object.commonjs [as api] (/usr/lib/node_modules/prettydiff/prettydiff.js:979:16)
    at pdNodeLocal__prettydiff (/usr/lib/node_modules/prettydiff/api/node-local.js:161:36)
    at pdNodeLocal__cliFile (/usr/lib/node_modules/prettydiff/api/node-local.js:975:22)
    at pdNodeLocal__fileComplete (/usr/lib/node_modules/prettydiff/api/node-local.js:1018:25)
```

I cannot provide the files used, but the bug does not occur on simpler files. Any thoughts on why / how this may be happening?

**Comment by prettydiff** [comment]
I am changing that line to this:

    if (options.diffspaceignore === true && change === "replace" && baseTextArray[baseStart] !== undefined && newTextArray[newStart] !== undefined && baseTextArray[baseStart].replace(/\s+/g, "") === newTextArray[newStart].replace(/\s+/g, "")) {

It will suppress those errors.

**Comment by bluepeter** [comment]
This issue is still occurring for me in 2.2.7. Removing `diffspaceignore: true` fixes it.
