### ISSUE TITLE
Twig: <!-- HTML comments --> cause JS error

### ISSUE THREAD

**Issue by amaisano** [prettydiff/prettydiff#635]
template.html.twig:

```twig
<!-- Button trigger modal -->
<a class="cursor-pointer" data-toggle="modal" data-target="#orderDetailsModal_{{ nid }}">
    {{ 'View Details'|t }}
</a>
```

Removing the HTML comment line resolves the issue.

```
[2020-04-02 23:39:10.976] [exthost] [error] TypeError: Cannot read property 'indexOf' of undefined
	at beautify_markup_apply_multiline_lev (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/node_modules/prettydiff/js/prettydiff.js:13635:48)
	at beautify_markup_apply_multiline (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/node_modules/prettydiff/js/prettydiff.js:13640:22)
	at beautify_markup_apply (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/node_modules/prettydiff/js/prettydiff.js:13694:25)
	at Object.beautify_markup [as markup] (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/node_modules/prettydiff/js/prettydiff.js:13730:10)
	at mode (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/node_modules/prettydiff/js/prettydiff.js:2044:58)
	at prettyDiff (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/extension/index.js:85:14)
	at Object.provideDocumentFormattingEdits (/Users/amaisano/.vscode/extensions/mblode.twig-language-2-0.9.0/extension/index.js:135:28)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:539
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:317)
	at I.provideDocumentFormattingEdits (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:510)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:610:102
	at V._withAdapter (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:832)
	at V.$provideDocumentFormattingEdits (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:610:80)
	at p._doInvokeHandler (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:688:464)
	at p._invokeHandler (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:688:156)
	at p._receiveRequest (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:686:766)
	at p._receiveOneMessage (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:623)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:683:791
	at l.fire (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:845)
	at v.fire (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:191:325)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:851:104
	at l.fire (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:845)
	at v.fire (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:717)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:192:897
	at l.fire (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:845)
	at p.acceptChunk (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188:897)
	at /Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188:249
	at Socket.t (/Users/amaisano/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by rahunak** [comment]
I have the same issue.
What about status of solution?
